/* ParseCpslTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. ParseCpslTokenManager.java */
package gate.jape.parser;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.regex.*;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import gate.Factory;
import gate.util.*;
import gate.jape.*;
import gate.jape.constraint.*;
import gate.event.*;
import org.apache.log4j.Logger;

/** Token Manager. */
@SuppressWarnings("unused")public class ParseCpslTokenManager implements ParseCpslConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 31;
         return jjMoveNfa_0(0, 0);
      case 34:
         jjmatchedKind = 36;
         return jjMoveNfa_0(0, 0);
      case 40:
         jjmatchedKind = 59;
         return jjMoveNfa_0(0, 0);
      case 41:
         jjmatchedKind = 60;
         return jjMoveNfa_0(0, 0);
      case 44:
         jjmatchedKind = 56;
         return jjMoveNfa_0(0, 0);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100L);
      case 46:
         jjmatchedKind = 54;
         return jjMoveNfa_0(0, 0);
      case 58:
         jjmatchedKind = 52;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1L);
      case 59:
         jjmatchedKind = 53;
         return jjMoveNfa_0(0, 0);
      case 61:
         jjmatchedKind = 63;
         return jjMoveNfa_0(0, 0);
      case 64:
         jjmatchedKind = 34;
         return jjMoveNfa_0(0, 0);
      case 67:
         return jjMoveStringLiteralDfa1_0(0xe00000L, 0x0L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x2100000L, 0x0L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x10000800L, 0x0L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x4000000L, 0x0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x41001000L, 0x0L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      case 91:
         jjmatchedKind = 61;
         return jjMoveNfa_0(0, 0);
      case 93:
         jjmatchedKind = 62;
         return jjMoveNfa_0(0, 0);
      case 99:
         return jjMoveStringLiteralDfa1_0(0xe00000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x2100000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x10000800L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x4000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x41001000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      case 123:
         jjmatchedKind = 57;
         return jjMoveNfa_0(0, 0);
      case 124:
         jjmatchedKind = 55;
         return jjMoveNfa_0(0, 0);
      case 125:
         jjmatchedKind = 58;
         return jjMoveNfa_0(0, 0);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 0);
   }
   switch(curChar)
   {
      case 43:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
         }
         break;
      case 45:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100L);
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L, active1, 0L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x1001000L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0xe00000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000800L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1001000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0xe00000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000800L, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(0, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 1);
   }
   switch(curChar)
   {
      case 62:
         if ((active1 & 0x100L) != 0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 2;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x1001000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000800L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0xe00000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x2100000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x1001000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000800L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0xe00000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x2100000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(0, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 2);
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x40100000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x1001000L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0xe00800L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x40100000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1001000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0xe00800L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 3);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 3);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 4;
         }
         break;
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x1001000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x14000000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x40f00000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x1001000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x14000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x40f00000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 4);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 4);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 5;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0xe00000L);
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 83:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0xe00000L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 5);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 5);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 6;
         }
         break;
      case 72:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0xe00000L);
      case 83:
         return jjMoveStringLiteralDfa7_0(active0, 0x4100000L);
      case 84:
         return jjMoveStringLiteralDfa7_0(active0, 0x60000000L);
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0xe00000L);
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x4100000L);
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x60000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 6);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 6);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 6);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 7;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x800L);
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 76:
         return jjMoveStringLiteralDfa8_0(active0, 0xe00000L);
      case 89:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x800L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0xe00000L);
      case 121:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 7);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 7);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 7);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 8;
         }
         break;
      case 69:
         return jjMoveStringLiteralDfa9_0(active0, 0xe00000L);
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x800L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0xe00000L);
      case 115:
         return jjMoveStringLiteralDfa9_0(active0, 0x800L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 8);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 8);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 8);
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa10_0(active0, 0x800L);
      case 82:
         return jjMoveStringLiteralDfa10_0(active0, 0xe00000L);
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x800L);
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0xe00000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 9);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 9);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 9);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 10;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L);
      case 70:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000L);
      case 83:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000L);
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L);
      case 102:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000L);
      case 115:
         return jjMoveStringLiteralDfa11_0(active0, 0x200000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 10);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 10);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 10);
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L);
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000L);
      case 84:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000L);
      case 98:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L);
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000L);
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 11);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 11);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 11);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa13_0(active0, 0x200000L);
      case 78:
         return jjMoveStringLiteralDfa13_0(active0, 0x400000L);
      case 79:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000L);
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0x200000L);
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x400000L);
      case 111:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 12);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 12);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 12);
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa14_0(active0, 0x400000L);
      case 82:
         return jjMoveStringLiteralDfa14_0(active0, 0xa00000L);
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x400000L);
      case 114:
         return jjMoveStringLiteralDfa14_0(active0, 0xa00000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 13);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 13);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 13);
   }
   switch(curChar)
   {
      case 83:
         return jjMoveStringLiteralDfa15_0(active0, 0x400000L);
      case 84:
         return jjMoveStringLiteralDfa15_0(active0, 0xa00000L);
      case 115:
         return jjMoveStringLiteralDfa15_0(active0, 0x400000L);
      case 116:
         return jjMoveStringLiteralDfa15_0(active0, 0xa00000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 14);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 14);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 14);
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa16_0(active0, 0xa00000L);
      case 72:
         return jjMoveStringLiteralDfa16_0(active0, 0x400000L);
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0xa00000L);
      case 104:
         return jjMoveStringLiteralDfa16_0(active0, 0x400000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 15);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 15);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 15);
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa17_0(active0, 0xa00000L);
      case 69:
         return jjMoveStringLiteralDfa17_0(active0, 0x400000L);
      case 100:
         return jjMoveStringLiteralDfa17_0(active0, 0xa00000L);
      case 101:
         return jjMoveStringLiteralDfa17_0(active0, 0x400000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 16);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 16);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 16);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 17;
         }
         else if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 17;
         }
         break;
      case 68:
         return jjMoveStringLiteralDfa18_0(active0, 0x400000L);
      case 100:
         return jjMoveStringLiteralDfa18_0(active0, 0x400000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 17);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 17);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 17);
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 18;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(0, 18);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 64;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 35)
                        kind = 35;
                     { jjCheckNAddStates(0, 7); }
                  }
                  else if ((0x100003600L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                     { jjCheckNAdd(21); }
                  }
                  else if ((0x280000000000L & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                  }
                  else if (curChar == 47)
                     { jjAddStates(11, 12); }
                  else if (curChar == 33)
                     { jjCheckNAddStates(13, 15); }
                  else if (curChar == 61)
                     { jjCheckNAddStates(16, 18); }
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 30;
                  else if (curChar == 59)
                     jjstateSet[jjnewStateCnt++] = 22;
                  else if (curChar == 46)
                     { jjCheckNAdd(16); }
                  if ((0x80000c0000000000L & l) != 0L)
                  {
                     if (kind > 32)
                        kind = 32;
                  }
                  else if (curChar == 60)
                     { jjCheckNAdd(2); }
                  else if (curChar == 62)
                     { jjCheckNAdd(2); }
                  break;
               case 1:
                  if ((0x5000000000000000L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               case 2:
                  if (curChar == 61 && kind > 33)
                     kind = 33;
                  break;
               case 3:
                  if (curChar == 62)
                     { jjCheckNAdd(2); }
                  break;
               case 4:
                  if (curChar == 60)
                     { jjCheckNAdd(2); }
                  break;
               case 14:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 15:
                  if (curChar == 46)
                     { jjCheckNAdd(16); }
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddStates(19, 21); }
                  break;
               case 18:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(19); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddTwoStates(19, 20); }
                  break;
               case 21:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 65)
                     kind = 65;
                  { jjCheckNAdd(21); }
                  break;
               case 22:
                  if (curChar == 59)
                     { jjCheckNAddStates(22, 25); }
                  break;
               case 23:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(22, 25); }
                  break;
               case 24:
                  if ((0x2400L & l) != 0L && kind > 67)
                     kind = 67;
                  break;
               case 25:
                  if (curChar == 13 && kind > 67)
                     kind = 67;
                  break;
               case 26:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 10 && kind > 67)
                     kind = 67;
                  break;
               case 28:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 59)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 31:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 61)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 34:
               case 36:
                  if (curChar == 61)
                     { jjCheckNAdd(33); }
                  break;
               case 35:
                  if (curChar == 33)
                     { jjCheckNAddStates(13, 15); }
                  break;
               case 37:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAdd(38); }
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(26, 32); }
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 41:
                  if (curChar != 46)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddStates(33, 35); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddStates(33, 35); }
                  break;
               case 44:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(45); }
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddTwoStates(45, 20); }
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(46, 47); }
                  break;
               case 48:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(49); }
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddTwoStates(49, 20); }
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(36, 38); }
                  break;
               case 52:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(53); }
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(53, 20); }
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAddStates(0, 7); }
                  break;
               case 55:
                  if (curChar == 47)
                     { jjAddStates(11, 12); }
                  break;
               case 56:
                  if (curChar == 47)
                     { jjCheckNAddStates(39, 42); }
                  break;
               case 57:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(39, 42); }
                  break;
               case 58:
                  if ((0x2400L & l) != 0L && kind > 66)
                     kind = 66;
                  break;
               case 59:
                  if (curChar == 13 && kind > 66)
                     kind = 66;
                  break;
               case 60:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 10 && kind > 66)
                     kind = 66;
                  break;
               case 62:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if (curChar == 42 && kind > 68)
                     kind = 68;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     { jjCheckNAdd(14); }
                  }
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 5:
                  if (curChar == 101 && kind > 48)
                     kind = 48;
                  break;
               case 6:
                  if (curChar == 117)
                     { jjCheckNAdd(5); }
                  break;
               case 7:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 115)
                     { jjCheckNAdd(5); }
                  break;
               case 10:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
               case 14:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjCheckNAdd(14); }
                  break;
               case 17:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(43, 44); }
                  break;
               case 20:
                  if ((0x5000000050L & l) != 0L && kind > 50)
                     kind = 50;
                  break;
               case 23:
                  { jjAddStates(22, 25); }
                  break;
               case 30:
                  if (curChar == 124 && kind > 68)
                     kind = 68;
                  break;
               case 33:
                  if (curChar == 126 && kind > 33)
                     kind = 33;
                  break;
               case 43:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(45, 46); }
                  break;
               case 47:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(47, 48); }
                  break;
               case 51:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(49, 50); }
                  break;
               case 57:
                  { jjAddStates(39, 42); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 23:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(22, 25); }
                  break;
               case 57:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(39, 42); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 64 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
private final int jjStopStringLiteralDfa_3(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1fe000000000L) != 0L)
            return 0;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_3(int pos, long active0){
   return jjMoveNfa_3(jjStopStringLiteralDfa_3(pos, active0), pos + 1);
}
private int jjMoveStringLiteralDfa0_3(){
   switch(curChar)
   {
      case 34:
         return jjStopAtPos(0, 47);
      case 92:
         return jjMoveStringLiteralDfa1_3(0x1fe000000000L);
      default :
         return jjMoveNfa_3(5, 0);
   }
}
private int jjMoveStringLiteralDfa1_3(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_3(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 34:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         break;
      case 39:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 43);
         break;
      case 92:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 44);
         break;
      case 98:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 40);
         break;
      case 102:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 41);
         break;
      case 110:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(1, 37);
         break;
      case 114:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(1, 38);
         break;
      case 116:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 39);
         break;
      default :
         break;
   }
   return jjStartNfa_3(0, active0);
}
private int jjMoveNfa_3(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 7;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if ((0xfffffffbffffffffL & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) != 0L && kind > 45)
                     kind = 45;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if ((0xffffffffefffffffL & l) != 0L)
                  {
                     if (kind > 46)
                        kind = 46;
                  }
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 0:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  if ((0x7e0000007eL & l) != 0L && kind > 45)
                     kind = 45;
                  break;
               case 6:
                  if ((0xffffffffefffffffL & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 5:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 46)
                     kind = 46;
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 7 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(9, 0);
}
private int jjMoveNfa_1(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 21;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 9:
                  if ((0x3ffe00000000000L & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     { jjCheckNAdd(0); }
                  }
                  else if ((0x100003600L & l) != 0L)
                  {
                     if (kind > 14)
                        kind = 14;
                     { jjCheckNAdd(1); }
                  }
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 10;
                  else if (curChar == 59)
                     jjstateSet[jjnewStateCnt++] = 2;
                  if (curChar == 47)
                     { jjAddStates(51, 52); }
                  break;
               case 0:
                  if ((0x3ffe00000000000L & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAdd(0); }
                  break;
               case 1:
                  if ((0x100003600L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAdd(1); }
                  break;
               case 2:
                  if (curChar == 59)
                     { jjCheckNAddStates(53, 56); }
                  break;
               case 3:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(53, 56); }
                  break;
               case 4:
                  if ((0x2400L & l) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 5:
                  if (curChar == 13 && kind > 16)
                     kind = 16;
                  break;
               case 6:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 10 && kind > 16)
                     kind = 16;
                  break;
               case 8:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 11:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 47)
                     { jjAddStates(51, 52); }
                  break;
               case 13:
                  if (curChar == 47)
                     { jjCheckNAddStates(57, 60); }
                  break;
               case 14:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(57, 60); }
                  break;
               case 15:
                  if ((0x2400L & l) != 0L && kind > 15)
                     kind = 15;
                  break;
               case 16:
                  if (curChar == 13 && kind > 15)
                     kind = 15;
                  break;
               case 17:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 10 && kind > 15)
                     kind = 15;
                  break;
               case 19:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 42 && kind > 17)
                     kind = 17;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 9:
               case 0:
                  if ((0x7fffffe97fffffeL & l) == 0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAdd(0); }
                  break;
               case 3:
                  { jjAddStates(53, 56); }
                  break;
               case 10:
                  if (curChar == 124 && kind > 17)
                     kind = 17;
                  break;
               case 14:
                  { jjAddStates(57, 60); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(53, 56); }
                  break;
               case 14:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(57, 60); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 21 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_4()
{
   return jjMoveNfa_4(1, 0);
}
private int jjMoveNfa_4(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 4;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 0:
                  if (curChar == 47)
                     kind = 70;
                  break;
               case 2:
                  if (curChar == 35)
                     kind = 70;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 4 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_2()
{
   return jjMoveNfa_2(1, 0);
}
private int jjMoveNfa_2(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 4;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 0:
                  if (curChar == 47)
                     kind = 19;
                  break;
               case 2:
                  if (curChar == 35)
                     kind = 19;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 4 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   38, 40, 41, 46, 47, 50, 51, 20, 38, 15, 39, 56, 63, 2, 33, 36, 
   2, 33, 34, 16, 17, 20, 23, 24, 26, 28, 40, 41, 46, 47, 50, 51, 
   20, 42, 43, 20, 50, 51, 20, 57, 58, 60, 62, 18, 19, 44, 45, 48, 
   49, 52, 53, 13, 20, 3, 4, 6, 8, 14, 15, 17, 19, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, "\41", null, null, "\100", null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, "\72", 
"\73", "\56", "\174", "\54", "\173", "\175", "\50", "\51", "\133", "\135", "\75", 
"\72\53", null, null, null, null, null, null, null, "\55\55\76", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         if (jjmatchedPos == 0 && jjmatchedKind > 71)
         {
            jjmatchedKind = 71;
         }
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 18)
         {
            jjmatchedKind = 18;
         }
         break;
       case 3:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_3();
         break;
       case 4:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_4();
         if (jjmatchedPos == 0 && jjmatchedKind > 69)
         {
            jjmatchedKind = 69;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        MoreLexicalActions();
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      case 37 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
               image.setLength(image.length() - 2); image.append("\u005cn");
         break;
      case 38 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
               image.setLength(image.length() - 2); image.append("\u005cr");
         break;
      case 39 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
               image.setLength(image.length() - 2); image.append("\u005ct");
         break;
      case 40 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
               image.setLength(image.length() - 2); image.append("\u005cb");
         break;
      case 41 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
               image.setLength(image.length() - 2); image.append("\u005cf");
         break;
      case 42 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
                image.setLength(image.length() - 2); image.append("\u005c"");
         break;
      case 43 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
                image.setLength(image.length() - 2); image.append("\u005c'");
         break;
      case 44 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
                image.setLength(image.length() - 2); image.append("\u005c\u005c");
         break;
      case 45 :
         image.append(input_stream.GetSuffix(jjimageLen));
         jjimageLen = 0;
               String digits = image.substring(image.length() - 4, image.length());
               image.setLength(image.length() - 6);
               image.append((char)Integer.parseInt(digits, 16));
         break;
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 47 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
        // image.setLength(image.length() - 1);
         matchedToken.image = image.toString();
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParseCpslTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public ParseCpslTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 64; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 5 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_PHASES",
   "PHASES_WITHIN_COMMENT",
   "IN_STRING",
   "WITHIN_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 2, -1, 1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 4, -1, 0, -1, -1, 
};
static final long[] jjtoToken = {
   0xfff7800ffff03801L, 0x181L, 
};
static final long[] jjtoSkip = {
   0xbc000L, 0x5eL, 
};
static final long[] jjtoSpecial = {
   0xbc000L, 0x5eL, 
};
static final long[] jjtoMore = {
   0x7ff000040000L, 0x20L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[64];
    private final int[] jjstateSet = new int[2 * 64];

    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    
    protected char curChar;
}
